#ifndef TPTALLER1_CONSTANTS_H
#define TPTALLER1_CONSTANTS_H

#define TEXT_WORLD_LEVEL_LABEL_KEY "world_level"
#define TEXT_WORLD_LEVEL_LABEL_VALUE "WORLD"
#define TEXT_WORLD_LEVEL_NUMBER_KEY "world_level_number"
#define TEXT_TIMER_LABEL_KEY "timer_label"
#define TEXT_TIMER_LABEL_VALUE "TIME"
#define TEXT_TIMER_VALUE_KEY "timer_value"
#define TEXT_DEFAULT_BACKGROUND_KEY "default_background"
#define TEXT_SERVER_DISCONNECTED_KEY "server_disconnected"
#define TEXT_DEFAULT_BACKGROUND_VALUE "DEFAULT"
#define TEXT_LEVEL_COMPLETED "LEVEL_COMPLETED"
#define TEXT_WORLD_LEVEL_LABEL_XPOS 600
#define TEXT_WORLD_LEVEL_LABEL_YPOS 10
#define TEXT_WORLD_LEVEL_NUMBER_XPOS 630
#define TEXT_WORLD_LEVEL_NUMBER_YPOS 30
#define TEXT_TIMER_LABEL_XPOS 700
#define TEXT_TIMER_LABEL_YPOS 10
#define TEXT_TIMER_VALUE_XPOS 710
#define TEXT_TIMER_VALUE_YPOS 30
#define TEXT_DEFAULT_BACKGROUND_XPOS 300
#define TEXT_DEFAULT_BACKGROUND_YPOS 10
#define TEXT_SERVER_DISCONNECTED_VALUE "Lost connection to server"
#define TEXT_LEVEL_COMPLETED_VALUE "Level completed!"
#define TEXT_POINTS_KEY "points"

#define BUMP_SOUND "BUMP"
#define COIN_SOUND "COIN"
#define GAME_OVER_SOUND "GAME_OVER"
#define HURRY_UP_SOUND "HURRY_UP"
#define JUMP_MEDIUM_SOUND "JUMP_MEDIUM"
#define JUMP_SMALL_SOUND "JUMP_SMALL"
#define MARIO_DIES_SOUND "MARIO_DIES"
#define POWER_UP_SOUND "POWER_UP"
#define POWER_UP_APPEARS_SOUND "POWER_UP_APPEARS"
#define STAGE_CLEAR_SOUND "STAGE_CLEAR"
#define STOMP_SOUND "STOMP"
#define WORLD_CLEAR_SOUND "WORLD_CLEAR"
#define MUSIC "MUSIC"

#define WHITE_COLOR {255,255,255}
#define RED_COLOR {255, 0, 0}
#define GREEN_COLOR {50,205,50}
#define PURPLE_COLOR {148,0,211}
#define YELLOW_COLOR {204,204,0}
#define BLACK_COLOR {0,0,0}

#endif //TPTALLER1_CONSTANTS_H
