//
// Created by DANIELA CARRERO on 2020-10-27.
//

#ifndef TPTALLER1_CONSTANTS_H
#define TPTALLER1_CONSTANTS_H

#define TEXT_WORLD_LEVEL_LABEL_KEY "world_level"
#define TEXT_WORLD_LEVEL_LABEL_VALUE "WORLD"
#define TEXT_WORLD_LEVEL_NUMBER_KEY "world_level_number"
#define TEXT_TIMER_LABEL_KEY "timer_label"
#define TEXT_TIMER_LABEL_VALUE "TIME"
#define TEXT_TIMER_VALUE_KEY "timer_value"
#define TEXT_WORLD_LEVEL_LABEL_XPOS 600
#define TEXT_WORLD_LEVEL_LABEL_YPOS 10
#define TEXT_WORLD_LEVEL_NUMBER_XPOS 630
#define TEXT_WORLD_LEVEL_NUMBER_YPOS 30
#define TEXT_TIMER_LABEL_XPOS 700
#define TEXT_TIMER_LABEL_YPOS 10
#define TEXT_TIMER_VALUE_XPOS 710
#define TEXT_TIMER_VALUE_YPOS 30

#define WHITE_COLOR {255,255,255}

#endif //TPTALLER1_CONSTANTS_H
